return {
      ["/api/token/:ownerid"]=
        {
          ["GET"]="tokens:read",
          ["POST"]="tokens:write"
        },
        ["/api/token/:ownerid/:tokenid"]=
        {
          ["GET"]="tokens:read",
          ["PUT,PATCH,DELETE"]="tokens:write"
        },
        ["/styles/:ownerid"]=
        {
          ["GET"]="styles:list",
          ["POST"]="styles:write"
         },
         ["/styles/:ownerid/duplicate"]=
        {
          ["POST"]="styles:write"
         },
           ["/styles/:ownerId/:styleId"]=
        {
          ["DELETE"]="styles:write"
         },
           ["/styles/:ownerId/:styleId/share"]=
        {
          ["GET"]="styles:read"
         },
           ["/styles/:ownerId/:styleId.zip"]=
        {
          ["GET"]="styles:read"
         },  
         ["/styles/:ownerid/:styleId/:subResourceId/static"]=
        {
          ["GET"]="styles:read"
         },  
         ["/styles/:ownerId/:styleId/:subResourceId/sprite/:name"]=
        {
          ["GET"]="styles:read"
         },             
          ["/styles/:ownerId/:styleId/draft/sprite/:iconId"]=
         {
          ["PUT,DELETE"]="styles:write"
         },
         ["/styles/:ownerId/:styleId/:subResourceId"]=
        {
          ["GET"]="styles:read"
         },  
         ["/styles/:ownerId/:styleId"]=
        {
          ["PATCH"]="styles:write"
         }, 
         ["/upload/tokens/:ownerid"]=
        {
          ["GET"]="tokens:write"
        }         
}
  